version: 2

before:
  hooks:
    # Build the frontend so it gets embedded into the binary.
    - sh -c 'if [ -f serve/frontend/package.json ]; then cd serve/frontend && npm ci && npm run build; else mkdir -p serve/frontend/dist && touch serve/frontend/dist/.gitkeep; fi'

builds:
  - id: vega
    main: ./cmd/vega
    binary: vega
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

brews:
  - skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"
    repository:
      owner: everydev1618
      name: homebrew-tap
      token: "{{ if .Env.HOMEBREW_TAP_TOKEN }}{{ .Env.HOMEBREW_TAP_TOKEN }}{{ else }}{{ .Env.GITHUB_TOKEN }}{{ end }}"
    directory: Formula
    homepage: https://github.com/everydev1618/govega
    description: AI Agent Orchestration CLI
    license: MIT
    install: |
      bin.install "vega"
    test: |
      system "#{bin}/vega", "version"

release:
  github:
    owner: everydev1618
    name: govega
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
